In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn import preprocessing

In [36]:
Data = pd.read_csv('AxisBankwGoogle.csv', index_col = None)
Data = Data.drop(['Unnamed: 0'], axis =1)
Data.head()

Date   Open    High    Low  Close  Adj_Close   Volume    SlowD  \
0  2007-03-08  84.73   90.00  82.41  87.22    53.0452  4318735  31.1875   
1  2007-03-09  87.98   93.58  85.40  91.28    55.5144  4839985  34.1700   
2  2007-03-12  90.20   94.59  90.20  91.81    55.8368  3205705  48.7047   
3  2007-03-13  91.42  100.24  91.42  98.72    60.0393  5450040  67.9299   
4  2007-03-14  97.00   97.00  92.70  94.56    57.5093  6524695  78.6763   

     SlowK    WILLR        ...              ADX       CCI   Chaikin A/D  \
0  28.0967 -69.6843        ...          43.0987  -85.9803 -8.869564e+07   
1  48.6871 -44.2022        ...          43.6819  -26.3314 -8.657741e+07   
2  69.3304 -40.6147        ...          43.6938   23.4586 -8.743178e+07   
3  85.7721  -7.2415        ...          41.1686  125.3260 -8.386021e+07   
4  80.9265 -27.0605        ...          38.8958   65.6804 -8.474028e+07   

           OBV  Axis Bank  isPartial  SMA3_GoogleTrends  EMA3_GoogleTrends  \
0  387207475.0        0.0      False                0.0                3.0   
1  392047460.0        0.0      False                0.0                3.0   
2  395253165.0        0.0      False                0.0                0.0   
3  400703205.0        0.0      False                0.0                0.0   
4  394178510.0        0.0      False                0.0                0.0   

   SMA5_GoogleTrends  EMA5_GoogleTrends  
0                0.0                5.0  
1                0.0                5.0  
2                0.0                5.0  
3                0.0                0.0  
4                0.0                0.0  

[5 rows x 24 columns]

# Creating Targets

In [37]:
Targets = pd.DataFrame()

Target1=[]
for i in range(0,len(Data['Open'])-1):
    if(Data.loc[i+1]['Open']-Data.loc[i]['Close']>=0):
        Target1.append(1)
    else:
        Target1.append(0)
Targets['Target1']=pd.Series(Target1)

Target2=[]
for i in range(0,len(Data['Open'])-1):
    if(Data.loc[i+1]['Open']-Data.loc[i]['Open']>=0):
        Target2.append(1)
    else:
        Target2.append(0)
Targets['Target2']=pd.Series(Target2)

In [38]:
Targets.head()

Target1  Target2
0        1        1
1        0        1
2        0        1
3        0        1
4        1        0

In [39]:
#Drop the Last row
Data = Data.drop(Data.index[len(Data)-1])
Data.head()

Date   Open    High    Low  Close  Adj_Close   Volume    SlowD  \
0  2007-03-08  84.73   90.00  82.41  87.22    53.0452  4318735  31.1875   
1  2007-03-09  87.98   93.58  85.40  91.28    55.5144  4839985  34.1700   
2  2007-03-12  90.20   94.59  90.20  91.81    55.8368  3205705  48.7047   
3  2007-03-13  91.42  100.24  91.42  98.72    60.0393  5450040  67.9299   
4  2007-03-14  97.00   97.00  92.70  94.56    57.5093  6524695  78.6763   

     SlowK    WILLR        ...              ADX       CCI   Chaikin A/D  \
0  28.0967 -69.6843        ...          43.0987  -85.9803 -8.869564e+07   
1  48.6871 -44.2022        ...          43.6819  -26.3314 -8.657741e+07   
2  69.3304 -40.6147        ...          43.6938   23.4586 -8.743178e+07   
3  85.7721  -7.2415        ...          41.1686  125.3260 -8.386021e+07   
4  80.9265 -27.0605        ...          38.8958   65.6804 -8.474028e+07   

           OBV  Axis Bank  isPartial  SMA3_GoogleTrends  EMA3_GoogleTrends  \
0  387207475.0        0.0      False                0.0                3.0   
1  392047460.0        0.0      False                0.0                3.0   
2  395253165.0        0.0      False                0.0                0.0   
3  400703205.0        0.0      False                0.0                0.0   
4  394178510.0        0.0      False                0.0                0.0   

   SMA5_GoogleTrends  EMA5_GoogleTrends  
0                0.0                5.0  
1                0.0                5.0  
2                0.0                5.0  
3                0.0                0.0  
4                0.0                0.0  

[5 rows x 24 columns]

In [40]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2817 entries, 0 to 2816
Data columns (total 24 columns):
Date                 2817 non-null object
Open                 2817 non-null float64
High                 2817 non-null float64
Low                  2817 non-null float64
Close                2817 non-null float64
Adj_Close            2817 non-null float64
Volume               2817 non-null int64
SlowD                2817 non-null float64
SlowK                2817 non-null float64
WILLR                2817 non-null float64
MACD                 2817 non-null float64
MACD_Signal          2817 non-null float64
MACD_Hist            2817 non-null float64
RSI                  2817 non-null float64
ADX                  2817 non-null float64
CCI                  2817 non-null float64
Chaikin A/D          2817 non-null float64
OBV                  2817 non-null float64
Axis Bank            2817 non-null float64
isPartial            2817 non-null bool
SMA3_GoogleTrends    2817 non-null floa

#  Prediction Using TimeSeries + Technical Indicators Data

## Predicting Target 1 [Open(i+1) - Close(i)] 

### Machine Learning Models

In [41]:
X = Data
X = X.drop('Date', axis = 1)
Y = Targets['Target1']
prediction = pd.DataFrame()
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state = 42,shuffle='False')
X_train = preprocessing.normalize(X_train)
X_test =  preprocessing.normalize(X_test)

### Decision Tree

In [44]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
prediction['DT'] = clf.predict(X_test)
print("Accuracy "+str(accuracy_score(y_test, prediction["DT"])))
print(classification_report(y_test, prediction['DT']))
conf_mat = confusion_matrix(y_test, prediction['DT'])
conf_mat_normalized = conf_mat.astype('float') / conf_mat.sum(axis=1)[:, np.newaxis]
print(conf_mat_normalized)

Accuracy 0.5548387096774193
             precision    recall  f1-score   support

          0       0.40      0.39      0.39       345
          1       0.64      0.65      0.65       585

avg / total       0.55      0.55      0.55       930

[[0.38550725 0.61449275]
 [0.34529915 0.65470085]]


### Logistic Regression

In [45]:
model = LogisticRegression()
model.fit(X_train,y_train)
prediction["LR"] = model.predict(X_test)
print(accuracy_score(y_test, prediction["LR"]))
print(classification_report(y_test, prediction['LR']))
conf_mat = confusion_matrix(y_test, prediction['LR'])
conf_mat_normalized = conf_mat.astype('float') / conf_mat.sum(axis=1)[:, np.newaxis]
print(conf_mat_normalized)

0.6290322580645161
             precision    recall  f1-score   support

          0       0.00      0.00      0.00       345
          1       0.63      1.00      0.77       585

avg / total       0.40      0.63      0.49       930

[[0. 1.]
 [0. 1.]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [46]:
# Support Vector Machine(SVM)
model = svm.SVC()
model.fit(X_train, y_train)  
prediction["SVM"] = model.predict(X_test)
print(accuracy_score(y_test, prediction["SVM"]))
print(classification_report(y_test, prediction['SVM']))
conf_mat = confusion_matrix(y_test, prediction['SVM'])
conf_mat_normalized = conf_mat.astype('float') / conf_mat.sum(axis=1)[:, np.newaxis]
print(conf_mat_normalized)

0.6290322580645161
             precision    recall  f1-score   support

          0       0.00      0.00      0.00       345
          1       0.63      1.00      0.77       585

avg / total       0.40      0.63      0.49       930

[[0. 1.]
 [0. 1.]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


### K Nearest Neighbours(KNN)

In [47]:
model = KNeighborsClassifier(n_neighbors=3)
print(model.fit(X_train,y_train))
prediction["KNN"] = model.predict(X_test)
print("Accuracy : " + str(accuracy_score(y_test, prediction["KNN"])))
print(classification_report(y_test, prediction['KNN']))
conf_mat = confusion_matrix(y_test, prediction['KNN'])
conf_mat_normalized = conf_mat.astype('float') / conf_mat.sum(axis=1)[:, np.newaxis]
print(conf_mat_normalized)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')
Accuracy : 0.5688172043010753
             precision    recall  f1-score   support

          0       0.40      0.33      0.36       345
          1       0.64      0.71      0.67       585

avg / total       0.55      0.57      0.56       930

[[0.33043478 0.66956522]
 [0.29059829 0.70940171]]


### Random Forest Classifier

In [48]:
rf = RandomForestClassifier(n_estimators=100)
print(rf.fit(X_train, y_train))
prediction["Random Forest Classifier"] = rf.predict(X_test)
print(accuracy_score(y_test, prediction["Random Forest Classifier"]))
print(classification_report(y_test, prediction['Random Forest Classifier']))
conf_mat = confusion_matrix(y_test, prediction['Random Forest Classifier'])
conf_mat_normalized = conf_mat.astype('float') / conf_mat.sum(axis=1)[:, np.newaxis]
print(conf_mat_normalized)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)
0.6290322580645161
             precision    recall  f1-score   support

          0       0.00      0.00      0.00       345
          1       0.63      1.00      0.77       585

avg / total       0.40      0.63      0.49       930

[[0. 1.]
 [0. 1.]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


### ADA Boost Classifier

In [49]:
model = AdaBoostClassifier()
print(model.fit(X_train,y_train))
prediction["ADA"] = model.predict(X_test)
print(accuracy_score(y_test, prediction["ADA"]))
print(classification_report(y_test, prediction['ADA']))
conf_mat = confusion_matrix(y_test, prediction['ADA'])
conf_mat_normalized = conf_mat.astype('float') / conf_mat.sum(axis=1)[:, np.newaxis]
print(conf_mat_normalized)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)
0.6204301075268818
             precision    recall  f1-score   support

          0       0.32      0.02      0.04       345
          1       0.63      0.97      0.76       585

avg / total       0.51      0.62      0.49       930

[[0.02028986 0.97971014]
 [0.02564103 0.97435897]]


In [50]:
for column in prediction.columns[:]:
    print("Accuracy of " + str(column) + ": "+ str(accuracy_score(y_test, prediction[column])))

Accuracy of DT: 0.5548387096774193
Accuracy of LR: 0.6290322580645161
Accuracy of SVM: 0.6290322580645161
Accuracy of KNN: 0.5688172043010753
Accuracy of Random Forest Classifier: 0.6290322580645161
Accuracy of ADA: 0.6204301075268818


## Predicting Target 2 [Open(i+1) - Open(i)] 

### Machine Learning Models

In [60]:
X = Data
X = X.drop('Date', axis = 1)
Y = Targets['Target2']
prediction = pd.DataFrame()
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.45, random_state = 52,shuffle='False')

### Decision Tree

In [61]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
prediction['DT'] = clf.predict(X_test)
print("Accuracy "+str(accuracy_score(y_test, prediction["DT"])))
print(classification_report(y_test, prediction['DT']))
conf_mat = confusion_matrix(y_test, prediction['DT'])
conf_mat_normalized = conf_mat.astype('float') / conf_mat.sum(axis=1)[:, np.newaxis]
print(conf_mat_normalized)

Accuracy 0.6293375394321766
             precision    recall  f1-score   support

          0       0.62      0.64      0.63       622
          1       0.64      0.62      0.63       646

avg / total       0.63      0.63      0.63      1268

[[0.63665595 0.36334405]
 [0.37770898 0.62229102]]


### Logistic Regression

In [62]:
model = LogisticRegression()
model.fit(X_train,y_train)
prediction["LR"] = model.predict(X_test)
print(accuracy_score(y_test, prediction["LR"]))
print(classification_report(y_test, prediction['LR']))
conf_mat = confusion_matrix(y_test, prediction['LR'])
conf_mat_normalized = conf_mat.astype('float') / conf_mat.sum(axis=1)[:, np.newaxis]
print(conf_mat_normalized)

0.5205047318611987
             precision    recall  f1-score   support

          0       0.51      0.45      0.48       622
          1       0.53      0.58      0.55       646

avg / total       0.52      0.52      0.52      1268

[[0.45498392 0.54501608]
 [0.41640867 0.58359133]]


In [63]:
# # Support Vector Machine(SVM)

model = svm.SVC()
model.fit(X_train, y_train)  

prediction["SVM"] = model.predict(X_test)

print(accuracy_score(y_test, prediction["SVM"]))

print(classification_report(y_test, prediction['SVM']))

conf_mat = confusion_matrix(y_test, prediction['SVM'])
conf_mat_normalized = conf_mat.astype('float') / conf_mat.sum(axis=1)[:, np.newaxis]
print(conf_mat_normalized)

0.5094637223974764
             precision    recall  f1-score   support

          0       0.00      0.00      0.00       622
          1       0.51      1.00      0.68       646

avg / total       0.26      0.51      0.34      1268

[[0. 1.]
 [0. 1.]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


### K Nearest Neighbours(KNN)

In [64]:
model = KNeighborsClassifier(n_neighbors=3)
print(model.fit(X_train,y_train))
prediction["KNN"] = model.predict(X_test)
print("Accuracy : " + str(accuracy_score(y_test, prediction["KNN"])))
print(classification_report(y_test, prediction['KNN']))
conf_mat = confusion_matrix(y_test, prediction['KNN'])
conf_mat_normalized = conf_mat.astype('float') / conf_mat.sum(axis=1)[:, np.newaxis]
print(conf_mat_normalized)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')
Accuracy : 0.4921135646687697
             precision    recall  f1-score   support

          0       0.48      0.49      0.49       622
          1       0.50      0.49      0.50       646

avg / total       0.49      0.49      0.49      1268

[[0.49196141 0.50803859]
 [0.50773994 0.49226006]]


### Random Forest Classifier

In [67]:
rf = RandomForestClassifier(n_estimators=100)
print(rf.fit(X_train, y_train))
prediction["Random Forest Classifier"] = rf.predict(X_test)
print(accuracy_score(y_test, prediction["Random Forest Classifier"]))
print(classification_report(y_test, prediction['Random Forest Classifier']))
conf_mat = confusion_matrix(y_test, prediction['Random Forest Classifier'])
conf_mat_normalized = conf_mat.astype('float') / conf_mat.sum(axis=1)[:, np.newaxis]
print(conf_mat_normalized)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)
0.7247634069400631
             precision    recall  f1-score   support

          0       0.71      0.74      0.72       622
          1       0.74      0.71      0.72       646

avg / total       0.73      0.72      0.72      1268

[[0.73794212 0.26205788]
 [0.2879257  0.7120743 ]]


### ADA Boost Classifier

In [68]:
model = AdaBoostClassifier()
print(model.fit(X_train,y_train))
prediction["ADA"] = model.predict(X_test)
print(accuracy_score(y_test, prediction["ADA"]))
print(classification_report(y_test, prediction['ADA']))
conf_mat = confusion_matrix(y_test, prediction['ADA'])
conf_mat_normalized = conf_mat.astype('float') / conf_mat.sum(axis=1)[:, np.newaxis]
print(conf_mat_normalized)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)
0.749211356466877
             precision    recall  f1-score   support

          0       0.74      0.76      0.75       622
          1       0.76      0.74      0.75       646

avg / total       0.75      0.75      0.75      1268

[[0.76045016 0.23954984]
 [0.26160991 0.73839009]]


In [58]:
for column in prediction.columns[:]:
    print("Accuracy of " + str(column) + ": "+ str(accuracy_score(y_test, prediction[column])))

Accuracy of DT: 0.6795698924731183
Accuracy of LR: 0.513978494623656
Accuracy of SVM: 0.5161290322580645
Accuracy of KNN: 0.46344086021505376
Accuracy of Random Forest Classifier: 0.7397849462365591
Accuracy of ADA: 0.7279569892473118
